import type { Metadata } from "next";
import { SUSE } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { Header } from "@/components/ui/home/header";
import Footer from "@/components/ui/home/footer";
import { ProgressiveBlur } from "@/components/ui/progressive-blur";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/next"

const suseMono = SUSE({
  variable: "--font-suse-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${suseMono.variable} antialiased font-suse relative
        `}
      >
        <Navbar />
        <Header />
        <main>
          <Suspense fallback={<>Loading...</>}>
            {children}
          </Suspense>
        </main>
        <ProgressiveBlur height="6rem" position="bottom" />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
